### ISSUE TITLE
無法爬取Python版

### ISSUE THREAD

**Issue by KenKHW** [shihjyun/PTTmineR#1]
您好
將board設成Python版時
```
rookie_miner %>% 
  mine_ptt(board = "Python",
           last.n.page = 10)
```
會出現 **Error in 1L:end_pos : 答案向量會太長**的錯誤訊息
請問我有哪邊操作錯誤嗎？

**Comment by shihjyun** [comment]
您好
請改成'Python'試試看
https://www.ptt.cc/bbs/Python/index.html
它是依照網址去找的
所以要確認一下網址的板名是什麼~

更新1:
不好意思，我剛剛用手機看，它會把 Python 自動變 python 所以誤會您大小寫輸入錯，我現在來看看

更新2: 
您好，您的操作並沒有錯，初步判斷原因是因為 Python 版沒有公告內容所以導致錯誤發生，謝謝回報，我明天會修正這個錯誤，請見諒！

**Comment by KenKHW** [comment]
謝謝你！！

**Comment by shihjyun** [comment]
目前「沒有公告」造成爬蟲錯誤的問題已修復，請安裝最新的版本

**Comment by shihjyun** [comment]
目前「沒有公告」造成爬蟲錯誤的問題已修復，請安裝最新的版本

**Comment by KenKHW** [comment]
不好意思，我剛剛有再重新安裝
`remotes::install_github("shihjyun/PTTmineR")`
但是跑
`rookie_miner %>% 
  mine_ptt(board = "Python",
           last.n.page = 10)`
還是會出現**Error in 1L:end_pos : 答案向量會太長**
請問我有哪邊沒注意到嗎?

**Comment by shihjyun** [comment]
@KenKHW 您好

我剛剛再重新安裝一次後確定可以執行的～
麻煩確認有沒有按照以下步驟：　
1. 刪除舊的 PTTmineR
2. 重新開啟 R/Rstudio
3. 執行 `remotes::install_github("shihjyun/PTTmineR")`

**Comment by KenKHW** [comment]
成功了！！謝謝你！
剛剛應該是沒有刪除就直接安裝新的。
